### ISSUE TITLE
Glad Giraffe - Conversion error

### ISSUE THREAD

**Issue by iUltimateLP** [PenguinToast/PenguinGUI#3]
Hi, pretty nice what you did with PenguinGUI, but theres one error in Glad Giraffe:
If I try to create a button, a label or something else, I get

```
Error: Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/objects/testobject/penguingui.lua"]:137: (LuaConversionException) Error converting LuaValue to type 'class Star::Maybe<class Star::Color>'
```

So it seems like that the old color things don't work that way in Glad Giraffe. I try to investigate that myself..

**Comment by iUltimateLP** [comment]
I opened a pull request where I fixed those !

**Comment by PenguinToast** [comment]
Merged. Thanks!
