### ISSUE TITLE
TextField cursor offset

### ISSUE THREAD

**Issue by Sethommar** [PenguinToast/PenguinGUI#6]
The cursor in TextField becomes incorrectly offset for some letters. It seems to be related to font scaling; as letters with widths that are evenly divisible by the scale factor do not exhibit this issue.

**Comment by PenguinToast** [comment]
Yep, unfortunately I was only able to get a very rough estimate of text width. I can't think of any good way to fix this, but if you come up with better scaling, feel free to submit a PR!
